### ISSUE TITLE
implement pagenation for b2share view

### ISSUE THREAD

**Issue by bne86** [EUDAT-B2DROP/b2sharebridge#11]
currently deposits are showed using a list which gets longer and longer

**Comment by apw1388** [comment]
Some filters for file upload was implemented with commit [c9ebabd](https://github.com/EUDAT-B2DROP/b2sharebridge/commit/c9ebabdfc332931082d2227ccd3b420ebf6adfc3) and fixed for mysql with commit [12a8ad6](https://github.com/EUDAT-B2DROP/b2sharebridge/commit/12a8ad6d652cab2efb0d67191195b93e0edfe26e).

I close this issue for now.

**Comment by bne86** [comment]
fix linting and add "failed" jobs to separate entry on "status" page.
