### ISSUE TITLE
Publishing of folders

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2DROP/b2sharebridge#29]
Publishing folders is technically possible in the current instance. However, it leads to B2SHARE records without any files.
The B2SHARE publication should be either 
1) be switched off for B2DROP folders or 
2) the files from a folder should be extracted. In this case it is not really obvious how to work with nested folders.

**Comment by bne86** [comment]
I disabled the TabView "B2SHARE" for folders already, but was not able to deactivate the FileList Button. When a user clicks the FileList Button, the TabView is opened, "B2SHARE" is not shown but the content of the B2SHARE tab is. Thats really strange behaviour, thanks for reporting.

**Comment by bne86** [comment]
situation already improved, keep it open.

**Comment by apw1388** [comment]
It is disabled for folder. If users want to upload the content of a folder, they have to select the files within the folder and select "B2SHARE".
