### ISSUE TITLE
Allow User to manage B2SHARE URL not Administrator

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2DROP/b2sharebridge#36]
As user may want to choose from different (local) B2Share installations.

**Comment by bne86** [comment]
I do not think this makes sense, in this case we must put many effort in hardening our code due to the fact that the remote API could try to inject code into the B2DROP server.

**Comment by mwinkens** [comment]
The user should open a ticket to add another B2SHARE server, since we support multiple b2share instances.
