### ISSUE TITLE
switching to default values is broken

### ISSUE THREAD

**Issue by apw1388** [EUDAT-B2DROP/b2sharebridge#44]
If you have customized values for max filesize or number of parallel deposits and remove them to go back to default values, the values are set to zero.

Reproduce:
- Set customized values for "# of uploads per user at the same time" and/or "MB maximum filesize per upload"
- Remove customized values
- See problem im JSON response from publish()

**Comment by thijscobben** [comment]
We have tried to test this but it worked on our machine. Not reproducible.
