### ISSUE TITLE
Support for multiple B2SHARE instances

### ISSUE THREAD

**Issue by hjhsalo** [EUDAT-B2DROP/b2sharebridge#56]
Could b2sharebridge support multiple B2SHARE instances?

This feature is needed for fi.b2drop.eudat.eu which CSC is offering to Finnish univeristies and research centers.

This is similar to #36, but instead of letting the user decide the URL, administrator should be able to define multiple B2SHARE instances and user can select a B2SHARE instance to use.

Since creating the draft requires user to set his/her B2SHARE API token, user should be able to set tokens for each of the B2SHARE instances (defined by administrator) in the user profile.

**Comment by apw1388** [comment]
This is now available since edeec5c commit in master.
