### ISSUE TITLE
Support uploading folders as an archive (.zip) to B2SHARE

### ISSUE THREAD

**Issue by hjhsalo** [EUDAT-B2DROP/b2sharebridge#57]
Since user can download a folder from B2DROP / Nextcloud as a zip file, would it be possible to allow similar feature for b2sharebridge?

User would select a folder and create a draft in B2SHARE, uploading the folder and it's contents as a zip file to the created draft.

**Comment by mwinkens** [comment]
The b2drop team already discussed this and there are technical and security reasons why we don't want to implement this for now.
