### ISSUE TITLE
appinfo/info.xml wrong id

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2DROP/b2sharebridge#6]
The id element, in file `appinfo/info.xml`,has the value `eudat`, this is wrong, it should carry the name: `b2share-bridge`.

When the app is enabled through ownCloud I get the following message: `No app name specified`

**Comment by bne86** [comment]
we are allowed to define what the value should be, for me its no problem to name it eudat but b2share-bridge is of course more explicit.

**Comment by dblommesteijn** [comment]
Ill change it as soon as I got an environment running.
