### ISSUE TITLE
Pop-up for missing APIP token is triggered at general sharing

### ISSUE THREAD

**Issue by apw1388** [EUDAT-B2DROP/b2sharebridge#76]
If a user wants to share data with other and has not B2SHAREBbridge token set, the pop-up about missing token is shown. This should not be the case. The pop-up should only be shown in b2sharebridge tab of the menu.

**Comment by mwinkens** [comment]
The popup is now shown only if the module is visible and only once. Sometimes the popup/modal is opening behind the file, which is out of my control and a new bug, but this is a way better behavior. Fixed for now
