### ISSUE TITLE
Store metadata for files

### ISSUE THREAD

**Issue by noumar** [EUDAT-B2DROP/b2sharebridge#8]
Feature request. User asked if it would be possible to store the filled metadata for the future. So that e.g if you interrupt the publishing or want to publish again the metadata would not be lost.

**Comment by bne86** [comment]
the bridge will only upload the file, the rest is done via the b2share UI, therefore there is no metadata in b2drop.

**Comment by noumar** [comment]
Wasn't the idea to use REST API to push both file and metadata?

**Comment by bne86** [comment]
for the old b2share, yes. but for the new one, one is able to create a deposit and close it later on. Not implementing (very complex) metadata forms that must be very adaptiv will reduce the development effort that we have to spent.
