### ISSUE TITLE
B2SHARE page text unreadable in dark mode

### ISSUE THREAD

**Issue by JohannesLares** [EUDAT-B2DROP/b2sharebridge#83]
When using B2DROP in dark mode, most of the text in B2SHARE tab is so low contrast, making it almost unreadable.

**Comment by mwinkens** [comment]
Hello @JohannesLares, which version are you using? With the newest version of the bridge for nextcloud 28 the dark mode was added/fixed. Also please provide a screenshot, because it does look fine for me (white on black?)

**Comment by JohannesLares** [comment]
I'm using NextCloud version 28 and latest version of b2sharebridge. I have noticed this issue also in EUDAT CDI B2DROP.

**Comment by mwinkens** [comment]
The current version on the eudat core service is not up to date yet and we are aware that there are issues with the previous dark mode, which will be handled at the next maintenance.

Can you please provide a screenshot? I checked out the current tag and I don't see any issues with the dark mode

**Comment by mwinkens** [comment]
@JohannesLares the latest version of the bridge is now in EUDAT CDI B2DROP and there shouldn't be any issues with the dark mode, as you can see [here](https://b2drop.eudat.eu/apps/b2sharebridge/)
